#!/bin/bash -x

(
  sysctl -w net.ipv4.neigh.default.gc_thresh3=4096 || true
  sysctl -w net.ipv4.neigh.default.gc_thresh2=2048 || true
) \
  > /etc/sysctl.d/100-bosh-nats.conf

if [ ! -f /var/vcap/data/nats/auth.json ]; then
   echo "{}" > /var/vcap/data/nats/auth.json
fi